create database customer_behaviour_project;
use customer_behaviour_project;
select* from customer_behaviour_project;

-- Q1 what is the total revenue generated by the male vs female customers;
select gender, sum(purchase_amount) as total_revenue
from customer_behaviour_project
group by gender;

-- Q2 which customer used discount but still spend more than average purchase amount
select customer_id, purchase_amount, item_purchased, discount_applied
from customer_behaviour_project
where discount_applied = 'Yes' and purchase_amount >= (select avg(purchase_amount) from customer_behaviour_project);

-- Q3 Which are the top 5 products with the highest review rating
select item_purchased, review_rating
from customer_behaviour_project
order by review_rating desc
limit 5;

-- compare the average purchase amount between standard and express shipping
select shipping_type, avg(purchase_amount) as average_amount
from customer_behaviour_project
where shipping_type in ('Standard', 'Express')
group by shipping_type;

-- compare average spend and total revenue between subscribers and non-subscribers
select subscription_status, avg(purchase_amount) as Average_spending, sum(purchase_amount) as total_revenue
from customer_behaviour_project
group by subscription_status;

-- Which top 5 products have the highest percentage of purchase when discount applied
select item_purchased,
	   round(
			sum(case when discount_applied = 'Yes' then 1 else 0 end)*100 / count(*)) as discount_percentage
from customer_behaviour_project
group by item_purchased
order by discount_percentage desc
limit 5;            

-- What are the top 3 most purchased products within the catagory
select item_purchased, category, total_purchases
from(
	select
		item_purchased, category,
        count(*) as total_purchases,
        rank() over (partition by category order by count(*) desc ) as rnk
	from customer_behaviour_project
    group by category, item_purchased
    )Ranked
    where rnk <= 3;

-- What is a revenue contribuition by each age group
select age_groups, sum(purchase_amount) as total_revenue
from customer_behaviour_project
group by age_groups;





